#lang racket

(require net/http-client)

(module+ test
  (require rackunit))

(define e2 ;
  #"<game><board><row><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row><row><cell><tile value =\"castle\"></tile></cell><cell><tile value =\"castle\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"mansion\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row><row><cell><tile value =\"bush\"></tile></cell><cell><tile value =\"floating-castle\"></tile></cell><cell><tile value =\"floating-castle\"></tile></cell><cell><tile value =\"mansion\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row><row><cell><tile value =\"bush\"></tile></cell><cell><tile value =\"castle\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row><row><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row><row><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row></board><current><tile value =\"crystal\"></tile></current><storehouse><tile value =\"none\"></tile></storehouse></game>")
(define e3 
  #"<game><board><row><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"hut\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row><row><cell><tile value=\"tree\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell></row><row><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"mansion\"></tile></cell><cell><tile value=\"blank\"></tile></cell></row><row><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"house\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell></row><row><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"grass\"></tile></cell><cell><tile value=\"grass\"></tile></cell><cell><tile value=\"bush\"></tile></cell></row><row><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"tree\"></tile></cell><cell><tile value=\"blank\"></tile></cell></row></board><current><tile value=\"grass\"></tile></current><storehouse><tile value=\"none\"></tile></storehouse></game>")
(define e4
  #"<game><board><row><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell></row><row><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell></row><row><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell></row><row><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell></row><row><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell></row><row><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell></row></board><current><tile value =\"imperial-robot\"></tile></current><storehouse><tile value =\"none\"></tile></storehouse></game>")
(define e5
  #"<game><board><row><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell></row><row><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell></row><row><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell></row><row><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell></row><row><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell></row><row><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell></row></board><current><tile value =\"imperial-robot\"></tile></current><storehouse><tile value =\"imperial-robot\"></tile></storehouse></game>")
(define e6 ;
  #"<game><board><row><cell><tile value =\"grass\"></tile></cell><cell><tile value =\"bush\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row><row><cell><tile value =\"hut\"></tile></cell><cell><tile value =\"grass\"></tile></cell><cell><tile value =\"bush\"></tile></cell><cell><tile value =\"bush\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row><row><cell><tile value =\"hut\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"bush\"></tile></cell><cell><tile value =\"mansion\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row><row><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"bush\"></tile></cell><cell><tile value =\"mansion\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row><row><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row><row><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row></board><current><tile value =\"grass\"></tile></current><storehouse><tile value =\"crystal\"></tile></storehouse></game>")

(define (client h p m u d)
  (define hc (http-conn-open h #:port p))
  (define-values (_ __ port) (http-conn-sendrecv! hc u
                       #:method m #:data d))
  (port->string port))

;(client "127.0.0.1" 8080 #"POST" "/move" e2)
;(client "127.0.0.1" 8080 #"POST" "/move" e3)
;(client "127.0.0.1" 8080 #"POST" "/move" e4)
;(client "127.0.0.1" 8080 #"POST" "/move" e5)
(client "127.0.0.1" 8080 #"POST" "/move" e6)