#lang racket

(require "basic-player-functions.rkt")

(module+ test
  (require rackunit))

(define e2 ;
  #"<game><board><row><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row><row><cell><tile value =\"castle\"></tile></cell><cell><tile value =\"castle\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"mansion\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row><row><cell><tile value =\"bush\"></tile></cell><cell><tile value =\"floating-castle\"></tile></cell><cell><tile value =\"floating-castle\"></tile></cell><cell><tile value =\"mansion\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row><row><cell><tile value =\"bush\"></tile></cell><cell><tile value =\"castle\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row><row><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row><row><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row></board><current><tile value =\"crystal\"></tile></current><storehouse><tile value =\"none\"></tile></storehouse></game>")
(define e3 
  #"<game><board><row><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"hut\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row><row><cell><tile value=\"tree\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell></row><row><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"mansion\"></tile></cell><cell><tile value=\"blank\"></tile></cell></row><row><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"house\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell></row><row><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"grass\"></tile></cell><cell><tile value=\"grass\"></tile></cell><cell><tile value=\"bush\"></tile></cell></row><row><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"blank\"></tile></cell><cell><tile value=\"tree\"></tile></cell><cell><tile value=\"blank\"></tile></cell></row></board><current><tile value=\"grass\"></tile></current><storehouse><tile value=\"none\"></tile></storehouse></game>")
(define e4
  #"<game><board><row><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell></row><row><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell></row><row><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell></row><row><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell></row><row><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell></row><row><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell></row></board><current><tile value =\"imperial-robot\"></tile></current><storehouse><tile value =\"none\"></tile></storehouse></game>")
(define e5
  #"<game><board><row><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell></row><row><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell></row><row><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell></row><row><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell></row><row><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell></row><row><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"house\"></tile></cell></row></board><current><tile value =\"imperial-robot\"></tile></current><storehouse><tile value =\"imperial-robot\"></tile></storehouse></game>")
(define e6 ;
  #"<game><board><row><cell><tile value =\"grass\"></tile></cell><cell><tile value =\"bush\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row><row><cell><tile value =\"hut\"></tile></cell><cell><tile value =\"grass\"></tile></cell><cell><tile value =\"bush\"></tile></cell><cell><tile value =\"bush\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row><row><cell><tile value =\"hut\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"bush\"></tile></cell><cell><tile value =\"mansion\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row><row><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"tree\"></tile></cell><cell><tile value =\"bush\"></tile></cell><cell><tile value =\"mansion\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row><row><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row><row><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell><cell><tile value =\"blank\"></tile></cell></row></board><current><tile value =\"grass\"></tile></current><storehouse><tile value =\"crystal\"></tile></storehouse></game>")

(module+ test
  (check-equal? 
   (client/post "127.0.0.1" 8080 "/move" e2)
   "<place><row value=\"1\"></row><column value=\"2\"></column></place>")
  (check-equal? 
   (client/post "127.0.0.1" 8080 "/move" e3)
   "<store></store>")
  (check-equal? 
   (client/post "127.0.0.1" 8080 "/move" e4)
   "<store></store>")
  (check-equal? 
   (client/post "127.0.0.1" 8080 "/move" e5)
   "<place><row value=\"0\"></row><column value=\"1\"></column></place>")
  (check-equal? 
   (client/post "127.0.0.1" 8080 "/move" e6)
   "<place><row value=\"2\"></row><column value=\"1\"></column></place>")
  (check-equal?
   (client/post "127.0.0.1" 8080 "/move" "<game></game>")
   "<error value=\"invalid-tree\"></error>"))

(module+ test
  (check-equal? (client/get "127.0.0.1" 8080 "/variant") 
                "<variant value=\"basic\"></variant>")
  (check-equal? (client/post "127.0.0.1" 8080 "/variant" #"void") 
                "<error value=\"invalid-method-or-path\"></error>"))

;(client "127.0.0.1" 8080 #"POST" "/move" e2)
;(client "127.0.0.1" 8080 #"POST" "/move" e3)
;(client "127.0.0.1" 8080 #"POST" "/move" e4)
;(client "127.0.0.1" 8080 #"POST" "/move" e5)
;(client "127.0.0.1" 8080 #"POST" "/move" e6)